import uuid
from datetime import datetime
from enum import Enum
from typing import Any

from pydantic import BaseModel, ConfigDict, Field


class ScreeningRecommendation(str, Enum):
    ADVANCE = "ADVANCE"
    HOLD = "HOLD"
    REJECT = "REJECT"


class SkillCategory(str, Enum):
    REQUIRED = "required"
    PREFERRED = "preferred"


class SkillMatch(BaseModel):
    skill: str = Field(..., description="Name of the evaluated skill")
    category: SkillCategory = Field(default=SkillCategory.REQUIRED, description="Skill requirement category")
    matched: bool = Field(..., description="True if evidence of the skill exists in the resume")
    evidence: str | None = Field(default=None, description="Direct quote or explanation from the resume")


class ScreeningEvaluation(BaseModel):
    """Structured result generated by the AI Screening Agent."""
    overall_score: float = Field(
        ...,
        ge=0.0,
        le=100.0,
        description="Overall fit score from 0.0 to 100.0 based on criteria match",
    )
    recommendation: ScreeningRecommendation = Field(
        ...,
        description="Final screening recommendation: ADVANCE, HOLD, or REJECT",
    )
    passed: bool = Field(
        ...,
        description="True if score meets or exceeds passing threshold (e.g. >= 65)",
    )
    summary: str = Field(
        ...,
        description="Concise executive summary of candidate qualification and fit for the role",
    )
    strengths: list[str] = Field(
        default_factory=list,
        description="Key strengths directly aligning with the job description",
    )
    weaknesses: list[str] = Field(
        default_factory=list,
        description="Identified gaps, missing skills, or areas needing verification",
    )
    skills_analysis: list[SkillMatch] = Field(
        default_factory=list,
        description="Itemized breakdown of required and preferred skills matching",
    )
    experience_assessment: str = Field(
        ...,
        description="Evaluation of years, seniority, and relevance of work history",
    )
    education_assessment: str = Field(
        ...,
        description="Evaluation of candidate's academic qualifications and credentials",
    )
    recommended_interview_questions: list[str] = Field(
        default_factory=list,
        description="Tailored questions for recruiters to probe during the interview phase",
    )


class ScreeningResultResponse(BaseModel):
    """API response model for persisted screening results."""
    id: uuid.UUID
    application_id: uuid.UUID
    score: float | None = None
    recommendation: str | None = None
    passed: bool | None = None
    summary: str | None = None
    details: dict[str, Any] | None = None
    created_at: datetime
    updated_at: datetime

    model_config = ConfigDict(from_attributes=True)


class ScreeningTriggerRequest(BaseModel):
    """Optional payload when manually requesting a re-screen or custom evaluation."""
    force_rescreen: bool = Field(
        default=False,
        description="If True, re-runs screening agent even if a result already exists.",
    )
    custom_notes: str | None = Field(
        default=None,
        description="Optional recruiter guidance to incorporate into the evaluation prompt.",
    )
